// client/src/components/CourseRecommendation.jsx
import { useContext, useEffect, useState } from 'react';
import useFetch from '../api/useRecommendationFetch';
import RecommendationStudentForm from './RecommendationStudentForm';
import Spinner from './shared/Spinner';
import RecommendationChat from './RecommendationChat';
import { FormSubmittedContext } from '../contexts/FormSubmittedContext';

export default function CourseRecommendation() {
  const { recommendationFormSubmitted, setRecommendationFormSubmitted } =
    useContext(FormSubmittedContext);

  const { loading, fetchData } = useFetch();
  const [data, setData] = useState(null);
  const [isVisible, setIsVisible] = useState(false);
  const [studentCharacteristics, setStudentCharacteristics] = useState('');

  useEffect(() => {
    if (!loading) {
      setIsVisible(true);
    }
  }, [loading]);

  const handleFormSubmit = async (properties) => {
    setStudentCharacteristics(properties.student_profile);
    setRecommendationFormSubmitted(true);
    setIsVisible(false);
    try {
      const result = await fetchData(properties);
      setData(result.data);
    } catch (error) {
      alert(`Sorry, something went wrong! ${error.message}`);
    }
  };

  return (
    <div className="h-full">
      {!recommendationFormSubmitted ? (
        <RecommendationStudentForm handleFormSubmit={handleFormSubmit} />
      ) : (
        <div className="h-full">
          {loading ? (
            <Spinner label="Analyzing your data, please wait for a moment!" />
          ) : (
            <div
              className={`h-full transition-opacity duration-1000 ${
                isVisible ? 'opacity-100' : 'opacity-0'
              }`}
            >
              <RecommendationChat
                studentCharacteristics={studentCharacteristics}
                courseInfo={data}
              />
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// client-svelte/src/routes/(authed)/course-recommendation/+page.svelte
<script lang="ts">
	import type { RecommendationProps } from '$/lib/types';
	import { PUBLIC_BASE_API_URL } from '$env/static/public';
	import RecommendationForm from './RecommendationForm.svelte';
	import Spinner from '$lib/components/Spinner.svelte';
	import RecommendationChat from './RecommendationChat.svelte';
	import { showLoadingOverlay } from '$/globalStore';
	import { fade } from 'svelte/transition';

	let isFetching: boolean = false;
	let formSubmitted: boolean = false;
	let courseInfo: { rationale: string; top_3_courses: any[] };
	let studentCharacteristics: string;

	const handleFormSubmit = async (properties: RecommendationProps) => {
		studentCharacteristics = properties?.student_profile;
		try {
			formSubmitted = true;
			isFetching = true;
			const response = await fetch(`${PUBLIC_BASE_API_URL}/recommendation`, {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify(properties)
			});
			if (!response.ok) {
				alert('Response was not ok!');
			}
			if (response.status == 200 && response.body) {
				const result = await response.json();
				courseInfo = result?.data;
			}
		} catch (error: any) {
			alert(`Something went wrong! ${error?.message}`);
		} finally {
			isFetching = false;
		}
	};

	$: $showLoadingOverlay = isFetching;
</script>

<svelte:head>
	<title>APAssist - Recommendation</title>
</svelte:head>

<section
	class="z-[1] flex flex-col gap-2 min-h-0 border-l bg-gray-100 border-[#DDD] overflow-hidden"
>
	<div class="h-full">
		{#if !formSubmitted}
			<RecommendationForm {handleFormSubmit} />
		{:else if isFetching}
			<div class="flex justify-center items-center h-full">
				<Spinner label="Analyzing your data, please wait for a moment!" />
			</div>
		{:else}
			<div in:fade={{ duration: 1500 }}>
				<div class="grid h-[calc(100vh-4.25rem)]">
					<RecommendationChat {studentCharacteristics} {courseInfo} />
				</div>
			</div>
		{/if}
	</div>
</section>
