// client/src/components/RecommendationChat.jsx
import {
  MainContainer,
  ChatContainer,
  MessageList,
  Message,
  MessageInput,
  TypingIndicator,
  Avatar,
} from '@chatscope/chat-ui-kit-react';
import { useState } from 'react';
import apassist_avatar from './../assets/avatar.png';
import student_avatar from './../assets/student_avatar.jpg';
import { getChatResponse } from '../api/getChatResponse';

export default function RecommendationChat({
  studentCharacteristics,
  courseInfo,
}) {
  const [messages, setMessages] = useState([
    {
      message: `Top 3 courses that best match to your profile are ${courseInfo.top_3_courses
        .map((course) => course.course_title)
        .join(', ')}`,
      sender: 'APAssist',
    },
    {
      message: 'Among them which one best fit me?',
      direction: 'outgoing',
      sender: 'user',
    },
    {
      message: courseInfo.rationale,
      sender: 'APAssist',
    },
    {
      message: 'You can ask any further question about this 3 courses!',
      sender: 'APAssist',
    },
  ]);
  const [isTyping, setIsTyping] = useState(false);

  const handleSend = async (message) => {
    const newMessage = {
      message,
      direction: 'outgoing',
      sender: 'user',
    };

    const newMessages = [...messages, newMessage];

    setMessages(newMessages);

    setIsTyping(true);
    await processQuery(newMessages);
  };

  async function processQuery(chatMessages) {
    // get stream response
    try {
      const response = await getChatResponse({
        conversation: chatMessages,
        top_3_courses: courseInfo.top_3_courses,
        studentCharacteristics,
      });
      const reader = response.body.getReader();

      let streamText = '';

      // eslint-disable-next-line no-constant-condition
      while (true) {
        const { done, value } = await reader.read();
        if (done) {
          break;
        }

        // Assuming the stream is sending text data
        const token = new TextDecoder().decode(value);
        streamText += token;
        setMessages([
          ...chatMessages,
          {
            message: streamText + '| ',
            sender: 'APAssist',
          },
        ]);
      }

      setIsTyping(false);

      setMessages([
        ...chatMessages,
        {
          message: streamText,
          sender: 'APAssist',
        },
      ]);
    } catch (error) {
      alert(error?.message);
      setIsTyping(false);
    }
  }
  return (
    <div className="h-full">
      <div className="w-full h-full">
        <MainContainer>
          <ChatContainer>
            <MessageList
              scrollBehavior="smooth"
              typingIndicator={
                isTyping ? (
                  <TypingIndicator content="APAssist is typing" />
                ) : null
              }
            >
              {messages.map((message, i) => {
                return (
                  <Message
                    style={{
                      marginTop: '10px',
                    }}
                    key={i}
                    model={message}
                    avatarPosition={message.sender === 'APAssist' ? 'tl' : 'tr'}
                  >
                    {message.sender === 'APAssist' ? (
                      <Avatar
                        src={apassist_avatar}
                        status="available"
                        name="Lilly"
                      />
                    ) : (
                      <Avatar src={student_avatar} name="Lilly" />
                    )}
                  </Message>
                );
              })}
            </MessageList>
            <MessageInput
              attachButton={false}
              placeholder="Type your query here"
              autoFocus
              onSend={handleSend}
              sendDisabled={false}
            />
          </ChatContainer>
        </MainContainer>
      </div>
    </div>
  );
}

// client-svelte/src/routes/(authed)/course-recommendation/RecommendationChat.svelte
<script lang="ts">
	import ChatMessages from '$/lib/components/Chat/ChatMessages.svelte';
	import type { IMessage } from '$/lib/types';
	import { PUBLIC_BASE_API_URL } from '$env/static/public';

	export let studentCharacteristics: string;
	export let courseInfo: { rationale: string; top_3_courses: any[] };

	let isFetching: boolean = false;
	let streamText: string = '| ';
	let messages: IMessage[] = [
		{
			message: `Top 3 courses that best match to your profile are ${courseInfo.top_3_courses
				.map((course) => course.course_title)
				.join(', ')}`,
			role: 'APAssist'
		},
		{
			message: 'Among them which one best fit me?',
			role: 'user'
		},
		{
			message: courseInfo.rationale,
			role: 'APAssist'
		},
		{
			message: 'You can ask any further question about this 3 courses!',
			role: 'APAssist'
		}
	];

	async function fetchResponse(prompt: string) {
		messages.push({ role: 'user', message: prompt });
		messages = messages;
		isFetching = true;

		try {
			const response = await fetch(`${PUBLIC_BASE_API_URL}/chat-courses`, {
				method: 'POST',
				headers: {
					Accept: 'text/event-stream',
					'Content-Type': 'application/json'
				},
				credentials: 'same-origin',
				body: JSON.stringify({
					conversation: messages,
					top_3_courses: courseInfo.top_3_courses,
					studentCharacteristics: studentCharacteristics
				})
			});

			if (!response.ok) {
				alert('Response was not ok!');
			}
			if (response.status == 200 && response.body) {
				isFetching = true;
				const reader = response.body.getReader();

				streamText = '';

				// eslint-disable-next-line no-constant-condition
				while (true) {
					const { done, value } = await reader.read();
					if (done) {
						break;
					}

					// Assuming the stream is sending text data
					const message = new TextDecoder().decode(value);
					streamText += message;
				}
				isFetching = false;
				messages.push({ role: 'APAssist', message: streamText });
				messages = messages;

				streamText = '| ';
			}
		} catch (error: any) {
			alert(`Something went wrong! ${error.message}`);
		} finally {
			isFetching = false;
		}
	}
</script>

<ChatMessages bind:isFetching bind:streamText bind:messages {fetchResponse} />
