// client-svelte/src/routes/(authed)/assistant/+page.svelte
<script lang="ts">
	import { PUBLIC_BASE_API_URL } from '$env/static/public';
	import Conversations from './Conversations.svelte';
	import Button from '$/lib/components/Button/Button.svelte';
	import AddIcons from '$/lib/icons/AddIcons.svelte';
	import ChatMessages from '$/lib/components/Chat/ChatMessages.svelte';
	import type { Message } from '$/lib/types';
	import { queryType } from './assistantStore';

	let streamText: string = '| ';
	let isFetching: boolean = false;

	let messages: Message[] = [
		{
			message: 'Hi, I am APAssist, a student service assistant. How can I help you today?',
			role: 'APAssist'
		}
	];

	async function fetchResponse(prompt: string) {
		messages.push({ role: 'user', message: prompt });
		messages = messages;
		isFetching = true;

		try {
			const response = await fetch(`${PUBLIC_BASE_API_URL}/query`, {
				method: 'POST',
				headers: {
					Accept: 'text/event-stream',
					'Content-Type': 'application/json'
				},
				credentials: 'same-origin',
				body: JSON.stringify({
					chatMessages: messages,
					queryType: $queryType
				})
			});

			if (!response.ok) {
				alert('Response was not ok!');
			}
			if (response.status == 200 && response.body) {
				isFetching = true;
				const reader = response.body.getReader();

				streamText = '';

				// eslint-disable-next-line no-constant-condition
				while (true) {
					const { done, value } = await reader.read();
					if (done) {
						break;
					}

					// Assuming the stream is sending text data
					const message = new TextDecoder().decode(value);
					streamText += message;
					console.log(streamText);
				}
				isFetching = false;
				messages.push({ role: 'APAssist', message: streamText });
				messages = messages;

				streamText = '| ';
			}
		} catch (error: any) {
			alert(`Something went wrong! ${error.message}`);
		} finally {
			isFetching = false;
		}
	}
</script>

<svelte:head>
	<title>APAssist - Chat</title>
</svelte:head>

<div
	class="grid grid-cols-[minmax(0,_auto)] md:grid-cols-[minmax(0,_auto),_20rem] h-[calc(100vh-4.25rem)]"
>
	<ChatMessages bind:isFetching bind:streamText bind:messages {fetchResponse} />

	<section
		class="z-[1] flex flex-col gap-2 min-h-0 bg-[#303338] border-l border-[#DDD] data-dark:border-[#2A2A2A] overflow-hidden"
	>
		<Button
			variant="outline"
			title="New chat"
			class="flex gap-1 m-4 mx-6 mt-3 p-4 text-[#4169E1] text-center border-2 border-[#4169E1] hover:bg-black rounded-full"
		>
			<AddIcons class="w-6 h-6" />
			New chat
		</Button>

		<Conversations />
	</section>
</div>

// client/src/components/Assistant.jsx
import {
  MainContainer,
  ChatContainer,
  MessageList,
  Message,
  MessageInput,
  TypingIndicator,
  Avatar,
} from '@chatscope/chat-ui-kit-react';
import { useContext, useState } from 'react';
import apassist_avatar from './../assets/avatar.png';
import student_avatar from './../assets/student_avatar.jpg';
import { getQueryResponse } from '../api/getQueryResponse';
import { QueryTypeContext } from '../contexts/QueryTypeContext';

export default function Assistant() {
  const { queryType } = useContext(QueryTypeContext);

  const [messages, setMessages] = useState([
    {
      message:
        "Hello, I'm APAssist, a virtual student service chatbot! How can I help you?",
      sender: 'APAssist',
    },
  ]);
  const [isTyping, setIsTyping] = useState(false);

  const handleSend = async (message) => {
    const newMessage = {
      message,
      direction: 'outgoing',
      sender: 'user',
    };

    const newMessages = [...messages, newMessage];

    setMessages(newMessages);

    setIsTyping(true);
    await processQuery(newMessages);
  };

  async function processQuery(chatMessages) {
    const prompt = chatMessages[chatMessages.length - 1].message;

    // get stream response
    try {
      const response = await getQueryResponse(prompt, queryType);
      const reader = response.body.getReader();

      let streamText = '';

      // eslint-disable-next-line no-constant-condition
      while (true) {
        const { done, value } = await reader.read();
        if (done) {
          break;
        }

        // Assuming the stream is sending text data
        const message = new TextDecoder().decode(value);
        streamText += message;
        setMessages([
          ...chatMessages,
          {
            message: streamText + '| ',
            sender: 'APAssist',
          },
        ]);
      }

      setIsTyping(false);

      setMessages([
        ...chatMessages,
        {
          message: streamText,
          sender: 'APAssist',
        },
      ]);
    } catch (error) {
      alert(error?.message);
      setIsTyping(false);
    }
  }
  return (
    <div className="h-[100%]">
      <div className="w-full h-[100%]">
        <MainContainer>
          <ChatContainer>
            <MessageList
              scrollBehavior="smooth"
              typingIndicator={
                isTyping ? (
                  <TypingIndicator content="APAssist is typing" />
                ) : null
              }
            >
              {messages.map((message, i) => {
                return (
                  <Message
                    style={{
                      marginTop: '10px',
                    }}
                    key={i}
                    model={message}
                    avatarPosition={message.sender === 'APAssist' ? 'tl' : 'tr'}
                  >
                    {message.sender === 'APAssist' ? (
                      <Avatar
                        src={apassist_avatar}
                        status="available"
                        name="Lilly"
                      />
                    ) : (
                      <Avatar src={student_avatar} name="Lilly" />
                    )}
                  </Message>
                );
              })}
            </MessageList>
            <MessageInput
              attachButton={false}
              placeholder="Type your query here"
              autoFocus
              onSend={handleSend}
              sendDisabled={false}
            />
          </ChatContainer>
        </MainContainer>
      </div>
    </div>
  );
}
